name: CI

on: [push]

jobs:
  all:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run linter and formatter
        run: npm run ci
      - name: Typecheck
        run: npm run tsc
      - name: Build bundle
        run: npm run build

